language: python
cache: pip
sudo: required
services:
  - docker
os:
  - linux
python:
  - "3.6"
script:
  - pip install -U pip pipenv
  - pipenv install --dev
  - WITH_INTEGRATION=1 pipenv run nose2 -s extractor
  - CELERY_ALWAYS_EAGER=1 pipenv run nose2 -s ./ --with-coverage --coverage-report=term-missing
after_success:
  - coveralls
  - "./tests/lintstats.sh"

deploy:
- provider: script
  script:
    ./deploy/make_and_push_images.sh api &&
    ./deploy/make_and_push_images.sh agent &&
    ./deploy/make_and_push_images.sh worker
  on:
    all_branches: true
- provider: script
  script:
    ./deploy/make_and_push_images.sh api &&
    ./deploy/make_and_push_images.sh agent &&
    ./deploy/make_and_push_images.sh worker &&
    ./deploy/install_helm.sh development &&
    ./deploy/publish_helm_chart.sh
  on:
    tags: true
