language: python
cache: pip
sudo: required
services:
  - docker
os:
  - linux
python:
  - "3.6"
script:
  - pip install -U pip pipenv
  - pipenv install --dev
  - docker pull redis
  - docker pull atlassianlabs/localstack
  - docker pull arxiv/fulltext-extractor:0.3
  - docker pull arxiv/preview:0.0
  - WITH_INTEGRATION=1 pipenv run nose2 -s extractor
  - WITH_INTEGRATION=1 pipenv run nose2 -s ./ --with-coverage --coverage-report=term-missing
after_success:
  - coveralls
  - "./tests/lint.sh fulltext"
  - "./tests/style.sh fulltext"
  - "./tests/type-check.sh fulltext"

deploy:
- provider: script
  script:
    ./deploy/make_and_push_images.sh
  on:
    all_branches: true
- provider: script
  script:
    ./deploy/make_and_push_images.sh
    ./deploy/install_helm.sh development &&
    ./deploy/publish_helm_chart.sh
  on:
    tags: true
