version: '3'

services:
  plaintext-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_VERSION: ARXIVNG-2462
    command: ["celery", "worker", "-A", "fulltext.worker.celery_app", "--loglevel=INFO", "-E", "--concurrency=1"]
    env_file:
      - ./worker.env
    networks:
      - plaintext-test
    volumes:
      # - docker:/var/lib/docker
      # - docker-run:/var/run
      - pdfs:/pdfs
      - data:/data
    depends_on:
      - plaintext-test-redis
      - plaintext-api

  plaintext-api:
    image: arxiv/plaintext-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_VERSION: ARXIVNG-2462
    # logging:
    #   driver: none
    command: ["uwsgi", "--ini", "/opt/arxiv/uwsgi.ini"]
    container_name: plaintext-api
    env_file:
      - ./api.env
      - ./jwt_secret.env
    volumes:
      - data:/data
    ports:
      - "8000:8000"
    networks:
      - plaintext-test
    depends_on:
      - plaintext-test-redis

  plaintext-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_VERSION: ARXIVNG-2462
    command: ["python", "-m", "fulltext.agent"]
    env_file:
      - ./agent.env
    networks:
      - plaintext-test
    depends_on:
      - plaintext-test-localstack
      - plaintext-worker
      - plaintext-api

networks:
  plaintext-test:

volumes:
  pdfs:
  data:
  docker:
  docker-run:
  dind-lib-dir:
