version: '3'

services:
  plaintext-worker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_VERSION: ARXIVNG-2462
    command: ["celery", "worker", "-A", "fulltext.worker.celery_app", "--loglevel=INFO", "-E", "--concurrency=1"]
    environment:
      REDIS_ENDPOINT: "plaintext-test-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      # KINESIS_VERIFY: ""
      # KINESIS_ENDPOINT: "plaintext-test-redis:4568"
      LOGLEVEL: 10
      CANONICAL_ENDPOINT: "http://mock-arxiv:8000"
      CANONICAL_VERIFY: 0
      PREVIEW_ENDPOINT: "http://mock-arxiv:8000/preview"
      PREVIEW_VERIFY: 0
      DOCKER_HOST: "tcp://plaintext-dind:2375"

      VAULT_ENABLED: "1"
      NAMESPACE: "production"
      KUBE_TOKEN: "fookubetoken"
      VAULT_HOST: "mock-plaintext-vault"
      VAULT_PORT: "8200"
      VAULT_ROLE: "plaintext"
      VAULT_CREDENTIAL: "foocredential"
      VAULT_SCHEME: "http"

      WAIT_FOR_SERVICES: 1
      WAIT_ON_STARTUP: 5

    networks:
      - plaintext-test
    volumes:
      # - docker:/var/lib/docker
      # - docker-run:/var/run
      - pdfs:/pdfs
      - data:/data
    depends_on:
      - plaintext-test-redis
      - plaintext-api

  plaintext-api:
    image: arxiv/plaintext-api
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_VERSION: ARXIVNG-2462
    # logging:
    #   driver: none
    command: ["uwsgi", "--ini", "/opt/arxiv/uwsgi.ini"]
    container_name: plaintext-api
    environment:
      REDIS_ENDPOINT: "plaintext-test-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      LOGLEVEL: 10
      JWT_SECRET: foosecret
      CANONICAL_ENDPOINT: "http://mock-arxiv:8000"
      CANONICAL_VERIFY: 0
      PREVIEW_ENDPOINT: "http://mock-arxiv:8000/preview"
      PREVIEW_VERIFY: 0
      VAULT_ENABLED: "1"
      NAMESPACE: "production"
      KUBE_TOKEN: "fookubetoken"
      VAULT_HOST: "mock-plaintext-vault"
      VAULT_PORT: "8200"
      VAULT_ROLE: "plaintext"
      VAULT_CREDENTIAL: "foocredential"
      VAULT_SCHEME: "http"

      WAIT_FOR_SERVICES: 1
      WAIT_ON_STARTUP: 5

    volumes:
      - data:/data
    ports:
      - "8000:8000"
    networks:
      - plaintext-test
    depends_on:
      - plaintext-test-redis

  plaintext-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_VERSION: ARXIVNG-2462
    command: ["python", "-m", "fulltext.agent"]
    environment:
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      KINESIS_VERIFY: "0"
      KINESIS_START_TYPE: "TRIM_HORIZON"
      KINESIS_ENDPOINT: "https://plaintext-test-localstack:4568"
      EXTRACTION_ENDPOINT: "http://api:8000"
      LOGLEVEL: 10
      LOGFILE: "/var/log/plaintext-agent-processor.log"
      MODE: "test"
    networks:
      - plaintext-test
    depends_on:
      - plaintext-test-localstack
      - plaintext-worker
      - plaintext-api

networks:
  plaintext-test:

volumes:
  pdfs:
  data:
  docker:
  docker-run:
  dind-lib-dir:
