version: '3'

services:
  plaintext-test-redis:
    image: redis
    container_name: plaintext-test-redis
    networks:
      - plaintext-test
    logging:
      driver: none
    # ports:
    #   - "6379:6379"

  plaintext-test-localstack:
    image: atlassianlabs/localstack
    container_name: plaintext-test-localstack
    networks:
      - plaintext-test
    ports:
      - "4572:4572"
      - "4568:4568"
    env_file:
      - ./localstack.env

  plaintext-dind:
    image: docker:18-dind
    container_name: plaintext-dind
    networks:
      - plaintext-test
    logging:
      driver: none
    # resources:
    #   requests:
    #     memory: "50Mi"
    #     cpu: "250m"
    #   limits:
    #     memory: "100Mi"
    #     cpu: "300m"
    privileged: true
    volumes:
    - dind-lib-dir:/var/lib/docker
    # - docker-run:/var/run
    - pdfs:/pdfs

  mock-arxiv:
    image: arxiv/mock-arxiv
    build:
      context: .
      dockerfile: Dockerfile-mock
    container_name: mock-arxiv
    env_file:
      - ./mock_arxiv.env
      - ./jwt_secret.env
    networks:
      - plaintext-test

  mock-plaintext-vault:
    image: arxiv/mock-plaintext-vault
    build:
      context: .
      dockerfile: Dockerfile-mock-vault
    container_name: mock-plaintext-vault
    env_file:
      - ./vault.env
      - ./jwt_secret.env
    networks:
      - plaintext-test

networks:
  plaintext-test:

volumes:
  pdfs:
  data:
  docker:
  docker-run:
  dind-lib-dir:
