version: '3'

services:
  plaintext-test-redis:
    image: redis
    container_name: plaintext-test-redis
    networks:
      - plaintext-test
    # ports:
    #   - "6379:6379"
  # plaintext-test-localstack:
  #   image: atlassianlabs/localstack
  #   container_name: plaintext-test-localstack
  #   networks:
  #     - plaintext-test
  #   ports:
  #     - "4572:4572"
  #     - "4568:4568"
  #   environment:
  #     USE_SSL: 'true'
  #     DEBUG: 'true'
  plaintext-worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    environment:
      REDIS_ENDPOINT: "plaintext-test-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      KINESIS_VERIFY: ""
      KINESIS_ENDPOINT: "plaintext-test-redis:4568"
      LOGLEVEL: 10
    networks:
      - plaintext-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pdfs:/pdfs
    depends_on:
      - plaintext-test-redis
      - plaintext-api
  plaintext-api:
    image: arxiv/plaintext-api
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: plaintext-api
    command: --http-socket :8000 -M -t 3000 --manage-script-name --processes 8 --threads 1 --async 100 --ugreen  --mount /=wsgi.py --logformat "%(addr) %(addr) - %(user_id)|%(session_id) [%(rtime)] [%(uagent)] \"%(method) %(uri) %(proto)\" %(status) %(size) %(micros) %(ttfb)"
    environment:
      REDIS_ENDPOINT: "plaintext-test-redis:6379"
      AWS_ACCESS_KEY_ID: "foo"
      AWS_SECRET_ACCESS_KEY: "bar"
      KINESIS_VERIFY: ""
      KINESIS_ENDPOINT: "plaintext-test-redis:4568"
      LOGLEVEL: 10
    ports:
      - "8000:8000"
    networks:
      - plaintext-test
    depends_on:
      - plaintext-test-redis
  # plaintext-agent:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-agent
  #   environment:
  #     AWS_ACCESS_KEY_ID: "foo"
  #     AWS_SECRET_ACCESS_KEY: "bar"
  #     CLOUDWATCH_ENDPOINT: "https://test-localstack:4582"
  #     DYNAMODB_ENDPOINT: "https://test-localstack:4569"
  #     KINESIS_ENDPOINT: "https://test-localstack:4568"
  #     KINESIS_VERIFY: ""
  #     DYNAMODB_VERIFY: ""
  #     CLOUDWATCH_VERIFY: ""
  #     EXTRACTION_ENDPOINT: "http://api:8000"
  #     LOGLEVEL: 10
  #     LOGFILE: "/var/log/plaintext-agent-processor.log"
  #     MODE: "test"
  #     JAVA_FLAGS: "-Dcom.amazonaws.sdk.disableCertChecking"
  #     AWS_CBOR_DISABLE: "true"
  #     INSTANCE_CREDENTIALS: ""
  #   networks:
  #     - plaintext-test
  #   depends_on:
  #     - plaintext-test-localstack
  #     - plaintext-worker
  #     - plaintext-api

networks:
  plaintext-test:
