apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: plaintext-ingress
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: plaintext-worker
    service-group: api

  annotations:
    ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
    # ingress.kubernetes.io/auth-url: http://{{ default "authenticator" .Values.authenticator.service }}.{{ .Values.namespace }}.svc.cluster.local/auth
    # ingress.kubernetes.io/auth-response-headers: Authorization
    ingress.kubernetes.io/limit-connections: "4"
    ingress.kubernetes.io/limit-rps: "4"
    ingress.kubernetes.io/rewrite-target: /

spec:
  tls:  # This will use the default certificate for the ingress controller.
  - hosts:
    - "{{ .Values.ingress.host }}"
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
      - path: "{{ default "/plaintext" .Values.subPath }}"
        backend:
          serviceName: "plaintext-api"
          servicePort: 80
